version: 0.2
phases:
  install:
    commands:
      - echo "install packages"
      - yum install -y httpd
      - systemctl start httpd
  pre_build:
    commands:
      - mv ./index.html /var/www/html/
      - ls -l /var/www/html/
      - httpd -S
      - systemctl status httpd
  build:
    commands:
      - echo "test start"
      - curl http://localhost/ || true
  post_build:
    commands:
      - echo "Build completed"
  #artifacts:
    #files:
      #- './result.txt'
